import Head from 'next/head';
import styles from '../styles/Home.module.scss';

import { Footer } from '../components';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Graph Exercise</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Graph Exercise</h1>

        <h2 className={styles.subtitle}>
          Developed by{' '}
          <a
            href='https://gerardogaravito.vercel.app/'
            target={'_blank'}
            rel='noreferrer'
          >
            Gerardo Garavito
          </a>
        </h2>
      </main>

      <Footer />
    </div>
  );
}
