import Head from 'next/head';
import styles from 'styles/Home.module.scss';
import { useStore } from 'store';

import { Footer, Header, NodesInput, NavigateButton } from 'components';

export default function Home() {
  const { nodes } = useStore();
  return (
    <div className={styles.container}>
      <Head>
        <title>Graph Exercise</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <NodesInput />

      {nodes.length > 0 && <NavigateButton to='/relations' text='siguiente' />}

      {/* <Footer /> */}
    </div>
  );
}
