import Head from 'next/head';
import styles from 'styles/Home.module.scss';
import { useStore } from 'store';

import { Header, Graph, NavigateButton, PathOrder } from 'components';

export default function Path() {
  const { nodes, dispatch, relations, pathOrder } = useStore();

  return (
    <div className={styles.container}>
      <Head>
        <title>Graph Exercise - Path</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      {relations.length > 0 && (
        <Graph relations={relations} pathOrder={pathOrder} />
      )}

      <PathOrder
        nodes={nodes}
        relations={relations}
        dispatch={dispatch}
        pathOrder={pathOrder}
      />

      <NavigateButton to='/relations' text='back' />
    </div>
  );
}
