import Head from 'next/head';
import styles from 'styles/Home.module.scss';
import { useStore } from 'store';

import {
  Footer,
  Header,
  Graph,
  NavigateButton,
  RelationsGenerator,
} from 'components';

export default function Relations() {
  const { nodes, dispatch, relations } = useStore();

  return (
    <div className={styles.container}>
      <Head>
        <title>Graph Exercise - Relations</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <RelationsGenerator
        nodes={nodes}
        dispatch={dispatch}
        relations={relations}
      />

      {relations.length > 0 && <Graph relations={relations} />}

      <NavigateButton to='/' text='atrás' />

      {/* <Footer /> */}
    </div>
  );
}
